package com.campus.entity;
// Generated 2016-11-15 21:31:56 by Hibernate Tools 3.5.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;

/**
 * TbGo generated by hbm2java
 */
@Entity
@Table(name = "tb_go", catalog = "campuschange")
public class Go implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8193452986222357711L;
	private Integer goid;
	private Integer goodId;
	private Integer orderId;
	private Integer isChange;

	public Go() {
	}

	public Go(Integer goodId, Integer orderId, Integer isChange) {
		this.goodId = goodId;
		this.orderId = orderId;
		this.isChange = isChange;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GOId", unique = true, nullable = false)
	public Integer getGoid() {
		return this.goid;
	}

	public void setGoid(Integer goid) {
		this.goid = goid;
	}

	@JoinColumn(name = "GoodId")
	public Integer getGoodId() {
		return this.goodId;
	}

	public void setGoodId(Integer goodId) {
		this.goodId = goodId;
	}

	@JoinColumn(name = "OrderId")
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "IsChange")
	public Integer getIsChange() {
		return this.isChange;
	}

	public void setIsChange(Integer isChange) {
		this.isChange = isChange;
	}

}
