package com.campus.entity;
// Generated 2016-11-15 21:31:56 by Hibernate Tools 3.5.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TbGood generated by hbm2java
 */
@Entity
@Table(name = "tb_good", catalog = "campuschange")
public class Good implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9000760861719887751L;
	private Integer goodId;
	private Integer userId;
	private String goodName;
	private Date createDate;
	private Date modifyDate;
	private String goodIntroduction;
	private double price;
	private Integer isOrdered;
	
	private String userName;
	private String datestr;
	public Good() {}

	public Good(Integer userId, String goodName, Date createDate, Date modifyDate,
			String goodIntroduction, double price,Integer isOrdered) {
		super();
		this.userId = userId;
		this.goodName = goodName;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.goodIntroduction = goodIntroduction;
		this.price = price;
		this.isOrdered = isOrdered;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GoodId", unique = true, nullable = false)
	public Integer getGoodId() {
		return this.goodId;
	}

	public void setGoodId(Integer goodId) {
		this.goodId = goodId;
	}

	@JoinColumn(name = "UserId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "GoodName", length = 20)
	public String getGoodName() {
		return this.goodName;
	}

	public void setGoodName(String goodName) {
		this.goodName = goodName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "GoodIntroduction")
	public String getGoodIntroduction() {
		return this.goodIntroduction;
	}

	public void setGoodIntroduction(String goodIntroduction) {
		this.goodIntroduction = goodIntroduction;
	}


	@Column(name="Price")
	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Transient
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	
	@Transient
	public String getDatestr() {
		return datestr;
	}

	public void setDatestr(String datestr) {
		this.datestr = datestr;
	}



	@Override
	public String toString() {
		return "Good [goodId=" + goodId + ", userId=" + userId + ", goodName=" + goodName + ", createDate=" + createDate
				+ ", modefyDate=" + modifyDate + ", goodIntroduction=" + goodIntroduction + ", price=" + price
				+ "]";
	}
	
	@Column(name="isOrdered")
	public Integer getIsOrdered() {
		return isOrdered;
	}

	public void setIsOrdered(Integer isOrdered) {
		this.isOrdered = isOrdered;
	}
	
	
	
}
