package com.campus.entity;
// Generated 2016-11-15 21:32:42 by Hibernate Tools 3.5.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbOrder generated by hbm2java
 */
@Entity
@Table(name = "tb_order", catalog = "campuschange")
public class Order implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2744721120820182179L;
	private Integer orderId;
	private Integer userId;
	private Date createDate;
	private Date modifyDate;
	private Integer orderStatus;

	public Order() {}

	public Order(Integer userId, Date createDate, Date modifyDate, Integer orderStatus) {
		this.userId = userId;
		this.createDate = createDate;
		this.modifyDate = modifyDate;
		this.orderStatus = orderStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OrderId", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@JoinColumn(name = "UserId")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreateDate", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ModifyDate", length = 19)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "OrderStatus")
	public Integer getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}


}
